// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/crawler.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 平台枚举。
type Platform int32

const (
	Platform_PLATFORM_UNSPECIFIED   Platform = 0
	Platform_PLATFORM_MERCARI       Platform = 1
	Platform_PLATFORM_YAHOO_AUCTION Platform = 2
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "PLATFORM_UNSPECIFIED",
		1: "PLATFORM_MERCARI",
		2: "PLATFORM_YAHOO_AUCTION",
	}
	Platform_value = map[string]int32{
		"PLATFORM_UNSPECIFIED":   0,
		"PLATFORM_MERCARI":       1,
		"PLATFORM_YAHOO_AUCTION": 2,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_crawler_proto_enumTypes[0].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_proto_crawler_proto_enumTypes[0]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_proto_crawler_proto_rawDescGZIP(), []int{0}
}

// 排序字段。
type SortBy int32

const (
	SortBy_SORT_BY_CREATED_TIME SortBy = 0 // 默认，按创建时间
	SortBy_SORT_BY_PRICE        SortBy = 1 // 价格
	SortBy_SORT_BY_SCORE        SortBy = 2 // 相关度/评分
	SortBy_SORT_BY_NUM_LIKES    SortBy = 3 // 点赞/收藏数
)

// Enum value maps for SortBy.
var (
	SortBy_name = map[int32]string{
		0: "SORT_BY_CREATED_TIME",
		1: "SORT_BY_PRICE",
		2: "SORT_BY_SCORE",
		3: "SORT_BY_NUM_LIKES",
	}
	SortBy_value = map[string]int32{
		"SORT_BY_CREATED_TIME": 0,
		"SORT_BY_PRICE":        1,
		"SORT_BY_SCORE":        2,
		"SORT_BY_NUM_LIKES":    3,
	}
)

func (x SortBy) Enum() *SortBy {
	p := new(SortBy)
	*p = x
	return p
}

func (x SortBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortBy) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_crawler_proto_enumTypes[1].Descriptor()
}

func (SortBy) Type() protoreflect.EnumType {
	return &file_proto_crawler_proto_enumTypes[1]
}

func (x SortBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortBy.Descriptor instead.
func (SortBy) EnumDescriptor() ([]byte, []int) {
	return file_proto_crawler_proto_rawDescGZIP(), []int{1}
}

// 排序方向。
type SortOrder int32

const (
	SortOrder_SORT_ORDER_DESC SortOrder = 0 // 默认，降序
	SortOrder_SORT_ORDER_ASC  SortOrder = 1 // 升序
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_DESC",
		1: "SORT_ORDER_ASC",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_DESC": 0,
		"SORT_ORDER_ASC":  1,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_crawler_proto_enumTypes[2].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_proto_crawler_proto_enumTypes[2]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_proto_crawler_proto_rawDescGZIP(), []int{2}
}

// 爬虫请求参数。
type FetchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础信息
	TaskId   string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Platform Platform `protobuf:"varint,2,opt,name=platform,proto3,enum=crawler.Platform" json:"platform,omitempty"`
	Keyword  string   `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	// 过滤条件
	MinPrice        int32    `protobuf:"varint,4,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice        int32    `protobuf:"varint,5,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	ExcludeKeywords []string `protobuf:"bytes,6,rep,name=exclude_keywords,json=excludeKeywords,proto3" json:"exclude_keywords,omitempty"`
	OnlyOnSale      bool     `protobuf:"varint,7,opt,name=only_on_sale,json=onlyOnSale,proto3" json:"only_on_sale,omitempty"`
	// 控制参数
	Limit         int32     `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	Sort          SortBy    `protobuf:"varint,9,opt,name=sort,proto3,enum=crawler.SortBy" json:"sort,omitempty"`
	Order         SortOrder `protobuf:"varint,10,opt,name=order,proto3,enum=crawler.SortOrder" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_proto_crawler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crawler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_proto_crawler_proto_rawDescGZIP(), []int{0}
}

func (x *FetchRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *FetchRequest) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PLATFORM_UNSPECIFIED
}

func (x *FetchRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *FetchRequest) GetMinPrice() int32 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *FetchRequest) GetMaxPrice() int32 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *FetchRequest) GetExcludeKeywords() []string {
	if x != nil {
		return x.ExcludeKeywords
	}
	return nil
}

func (x *FetchRequest) GetOnlyOnSale() bool {
	if x != nil {
		return x.OnlyOnSale
	}
	return false
}

func (x *FetchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FetchRequest) GetSort() SortBy {
	if x != nil {
		return x.Sort
	}
	return SortBy_SORT_BY_CREATED_TIME
}

func (x *FetchRequest) GetOrder() SortOrder {
	if x != nil {
		return x.Order
	}
	return SortOrder_SORT_ORDER_DESC
}

// 商品信息。
type Item struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 核心数据
	SourceId string `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price    int32  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl string `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	ItemUrl  string `protobuf:"bytes,5,opt,name=item_url,json=itemUrl,proto3" json:"item_url,omitempty"`
	// 元数据
	Platform      Platform `protobuf:"varint,6,opt,name=platform,proto3,enum=crawler.Platform" json:"platform,omitempty"`
	Status        string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Currency      string   `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_crawler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crawler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_crawler_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Item) GetItemUrl() string {
	if x != nil {
		return x.ItemUrl
	}
	return ""
}

func (x *Item) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PLATFORM_UNSPECIFIED
}

func (x *Item) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Item) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// 抓取响应。
type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalFound    int32                  `protobuf:"varint,2,opt,name=total_found,json=totalFound,proto3" json:"total_found,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TaskId        string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_proto_crawler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crawler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_proto_crawler_proto_rawDescGZIP(), []int{2}
}

func (x *FetchResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *FetchResponse) GetTotalFound() int32 {
	if x != nil {
		return x.TotalFound
	}
	return 0
}

func (x *FetchResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *FetchResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

var File_proto_crawler_proto protoreflect.FileDescriptor

const file_proto_crawler_proto_rawDesc = "" +
	"\n" +
	"\x13proto/crawler.proto\x12\acrawler\"\xdc\x02\n" +
	"\fFetchRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12-\n" +
	"\bplatform\x18\x02 \x01(\x0e2\x11.crawler.PlatformR\bplatform\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x1b\n" +
	"\tmin_price\x18\x04 \x01(\x05R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x05 \x01(\x05R\bmaxPrice\x12)\n" +
	"\x10exclude_keywords\x18\x06 \x03(\tR\x0fexcludeKeywords\x12 \n" +
	"\fonly_on_sale\x18\a \x01(\bR\n" +
	"onlyOnSale\x12\x14\n" +
	"\x05limit\x18\b \x01(\x05R\x05limit\x12#\n" +
	"\x04sort\x18\t \x01(\x0e2\x0f.crawler.SortByR\x04sort\x12(\n" +
	"\x05order\x18\n" +
	" \x01(\x0e2\x12.crawler.SortOrderR\x05order\"\xea\x01\n" +
	"\x04Item\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12\x19\n" +
	"\bitem_url\x18\x05 \x01(\tR\aitemUrl\x12-\n" +
	"\bplatform\x18\x06 \x01(\x0e2\x11.crawler.PlatformR\bplatform\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\"\x93\x01\n" +
	"\rFetchResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.crawler.ItemR\x05items\x12\x1f\n" +
	"\vtotal_found\x18\x02 \x01(\x05R\n" +
	"totalFound\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId*V\n" +
	"\bPlatform\x12\x18\n" +
	"\x14PLATFORM_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PLATFORM_MERCARI\x10\x01\x12\x1a\n" +
	"\x16PLATFORM_YAHOO_AUCTION\x10\x02*_\n" +
	"\x06SortBy\x12\x18\n" +
	"\x14SORT_BY_CREATED_TIME\x10\x00\x12\x11\n" +
	"\rSORT_BY_PRICE\x10\x01\x12\x11\n" +
	"\rSORT_BY_SCORE\x10\x02\x12\x15\n" +
	"\x11SORT_BY_NUM_LIKES\x10\x03*4\n" +
	"\tSortOrder\x12\x13\n" +
	"\x0fSORT_ORDER_DESC\x10\x00\x12\x12\n" +
	"\x0eSORT_ORDER_ASC\x10\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_proto_crawler_proto_rawDescOnce sync.Once
	file_proto_crawler_proto_rawDescData []byte
)

func file_proto_crawler_proto_rawDescGZIP() []byte {
	file_proto_crawler_proto_rawDescOnce.Do(func() {
		file_proto_crawler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_crawler_proto_rawDesc), len(file_proto_crawler_proto_rawDesc)))
	})
	return file_proto_crawler_proto_rawDescData
}

var file_proto_crawler_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_crawler_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_crawler_proto_goTypes = []any{
	(Platform)(0),         // 0: crawler.Platform
	(SortBy)(0),           // 1: crawler.SortBy
	(SortOrder)(0),        // 2: crawler.SortOrder
	(*FetchRequest)(nil),  // 3: crawler.FetchRequest
	(*Item)(nil),          // 4: crawler.Item
	(*FetchResponse)(nil), // 5: crawler.FetchResponse
}
var file_proto_crawler_proto_depIdxs = []int32{
	0, // 0: crawler.FetchRequest.platform:type_name -> crawler.Platform
	1, // 1: crawler.FetchRequest.sort:type_name -> crawler.SortBy
	2, // 2: crawler.FetchRequest.order:type_name -> crawler.SortOrder
	0, // 3: crawler.Item.platform:type_name -> crawler.Platform
	4, // 4: crawler.FetchResponse.items:type_name -> crawler.Item
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_crawler_proto_init() }
func file_proto_crawler_proto_init() {
	if File_proto_crawler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_crawler_proto_rawDesc), len(file_proto_crawler_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_crawler_proto_goTypes,
		DependencyIndexes: file_proto_crawler_proto_depIdxs,
		EnumInfos:         file_proto_crawler_proto_enumTypes,
		MessageInfos:      file_proto_crawler_proto_msgTypes,
	}.Build()
	File_proto_crawler_proto = out.File
	file_proto_crawler_proto_goTypes = nil
	file_proto_crawler_proto_depIdxs = nil
}
